class EnvVars:
    test_environment = "TEST_ENVIRONMENT"
    microservice_proto = "MICROSERVICE_PROTO"
    microservice_host = "MICROSERVICE_HOST"
    local_microservice_port = "LOCAL_MICROSERVICE_PORT"
    remote_microservice_port = "REMOTE_MICROSERVICE_PORT"
    db_host = "DB_HOST"
    db_port = "DB_PORT"
    db_username = "DB_USERNAME"
    db_password = "DB_PASSWORD"
    db_name = "DB_NAME"
    auth_port = "AUTH_PORT"
    auth_username = "AUTH_USERNAME"
    auth_password = "AUTH_PASSWORD"
    auth_path = "AUTH_PATH"
    cube_port = "CUBE_PORT"


class Defaults:
    test_environment = "local"
    microservice_proto = "http"
    microservice_host = "localhost"
    local_microservice_port = "80"
    remote_microservice_port = "80"
    db_host = "localhost"
    db_port = "5432"
    db_username = "user"
    db_password = "password"
    db_name = "database"
    auth_port = "8080"
    auth_username = "auth_user"
    auth_password = "auth_password"
    auth_path = "/auth"
    cube_port = "4000"
