[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sbilifeco-boundaries-llm"
version = "0.1.0"
description = "description"
dependencies = [
    "pydantic>=2.11.5",
    "sbilifeco-models-base>=0.1.0",
    "sbilifeco-models-db-metadata>=0.1.0"
]
