services:
    traefik:
        image: sbilifedockeradmin/traefik:latest
        restart: always
        networks:
            - nl2sql
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command:
            - --api.insecure=true
            - --providers.docker=true
            - --accesslog=true
            - --log.level=DEBUG
            - --providers.docker.constraints=Label(`application`, `nl2sql`)
        ports:
            - 11200:80
            - 11201:8080
    redis:
        image: sbilifedockeradmin/redis:latest
        restart: always
        networks:
            - nl2sql
        volumes:
            - ./.local/.redis:/data
    kafka:
        image: sbilifedockeradmin/kafka:latest
        restart: always
        networks:
            - nl2sql
        ports:
            - 11202:9094
        env_file: .local/kafka.env
    sqlalchemy-gateway:
        image: sbilifedockeradmin/sqlalchemy-gateway:latest
        restart: always
        networks:
            - nl2sql
        environment:
            - DEFINITIONS_PATH=/var/lib/metadata
        volumes:
            - ./.local/.alchemy:/var/lib/metadata
        labels:
            - traefik.http.routers.metadata-storage.rule=PathPrefix(`/api/v1/db-metadata`)
            - application=nl2sql
    redis-gateway:
        image: sbilifedockeradmin/redis-gateway:latest
        restart: always
        networks:
            - nl2sql
        environment:
            - REDIS_HOST=redis
        labels:
            - traefik.http.routers.session-data.rule=PathPrefix(`/api/v1/session-data`)
            - traefik.http.routers.session-data.service=session-data
            - traefik.http.services.session-data.loadBalancer.server.url=http://redis-gateway:80
            - traefik.http.routers.population-counter.rule=PathPrefix(`/api/v1/population-counter`)
            - traefik.http.routers.population-counter.service=population-counter
            - traefik.http.services.population-counter.loadBalancer.server.url=http://redis-gateway:81
            - application=nl2sql
    qdrant-gateway:
        image: sbilifedockeradmin/qdrant-gateway:latest
        restart: always
        networks:
            - nl2sql
        extra_hosts:
            - "host.docker.internal:host-gateway"
        env_file: .local/qdrant-gateway.env
        labels:
            - traefik.http.routers.vectoriser.rule=PathPrefix(`/api/v1/vectors`)
            - traefik.http.routers.vectoriser.service=vectoriser
            - traefik.http.services.vectoriser.loadBalancer.server.url=http://qdrant-gateway
            - traefik.http.routers.vector-repo.rule=PathPrefix(`/api/v1/vectorised-data`)
            - traefik.http.routers.vector-repo.service=vector-repo
            - traefik.http.services.vector-repo.loadBalancer.server.url=http://qdrant-gateway:81
            - application=nl2sql
    kafka-as-repo:
        image: sbilifedockeradmin/kafka-as-repo:latest
        restart: always
        networks:
            - nl2sql
        environment:
            - KAFKA_URL=kafka:9092
            - ANSWER_TIMEOUT=2
        labels:
            - traefik.http.routers.non-sql-answer-repo.rule=PathPrefix(`/api/v1/query-flow-answers`)
            - application=nl2sql
    static-web-server:
        image: sbilifedockeradmin/static-web-server:latest
        restart: always
        networks:
            - nl2sql
        volumes:
            - ./.local/analytics:/var/www/html/analytics:ro
            - ./.local/.query-flow-batch-test:/var/www/html/test-results/query-flow:ro
            - ./.local/.auth-pages/auth:/var/www/html/auth:ro
        labels:
            - traefik.http.routers.analytics.rule=PathPrefix(`/analytics`)
            - traefik.http.routers.test-results.rule=PathPrefix(`/test-results`)
            - traefik.http.routers.auth-pages.rule=PathPrefix(`/auth/pages`) || PathPrefix(`/auth/js`) || PathPrefix(`/auth/css`)
            - application=nl2sql
    forward-auth-server:
        image: sbilifedockeradmin/forwardauth-auth-service:latest
        restart: always
        networks:
            - nl2sql
        env_file: .local/forward-auth-server.env
        volumes:
            - ./.local/.auth-users/users.yaml:/etc/auth-service/users.yaml:ro
        labels:
            - traefik.http.routers.forward-auth.rule=PathPrefix(`/auth/step`)
            - traefik.http.middlewares.forward-auth.forwardauth.address=http://forward-auth-server:80/auth/step/validate
            - traefik.http.middlewares.forward-auth.forwardauth.trustForwardHeader=true
            - application=nl2sql
    unified-mcp-server:
        image: sbilifedockeradmin/unified-mcp-server:latest
        restart: always
        networks:
            - nl2sql
        environment:
            - POPULATION_COUNTER_HOST=redis-gateway
            - POPULATION_COUNTER_PORT=81
        labels:
            - traefik.http.routers.unified-mcp-server.rule=PathPrefix(`/mcp`)
            - application=nl2sql
    file-read-update-service:
        image: sbilifedockeradmin/file-read-update-service:latest
        restart: always
        networks:
            - nl2sql
        environment:
            - CONFIG_PATH=/etc/files.yaml
        volumes:
            - ./.local/files.yaml:/etc/files.yaml:ro
            - ./.local/.prompts:/var/lib/prompts:rw
            - ./.local/.alchemy:/var/lib/alchemy:rw
        labels:
            - traefik.http.routers.file-read-update.rule=PathPrefix(`/api/v1/updatable-objects`)
            - application=nl2sql
    query-flow:
        image: sbilifedockeradmin/query-flow:latest
        restart: always
        networks:
            - nl2sql
        env_file: .local/query-flow.env
        volumes:
            - ./.local/.prompts:/app/.prompts
            - ./.local/analytics/query-flow:/var/log/nl2sql/query-flow:rw
        labels:
            - traefik.http.routers.query-flow.rule=PathPrefix(`/api/v1/query-flow`)
            - application=nl2sql
    answer-notify-flow:
        image: sbilifedockeradmin/answer-notify-flow:latest
        restart: always
        networks:
            - nl2sql
        environment:
            - KAFKA_URL=kafka:9092
            - ANSWER_REPO_HOST=kafka-as-repo
            - MAX_ITEMS=25
            - WEB_PAGE_PATH=/var/lib/sbilifeco/analytics/query-flow-answers/index.html
            - TEMPLATE_PATH=/var/lib/sbilifeco/templates/template.html
        volumes:
            - ./.local/analytics:/var/lib/sbilifeco/analytics:rw
            - ./.local/.jinja-templates:/var/lib/sbilifeco/templates:ro
        labels:
            - traefik.http.routers.answer-notify-flow.rule=PathPrefix(`/api/v1/answer-notify-requests`)
            - application=nl2sql
    query-generator-ui:
        image: sbilifedockeradmin/query-generator-ui:latest
        restart: always
        networks:
            - nl2sql
        env_file: .local/query-generator-ui.env
        ports:
            - 11206:80
        volumes:
            - ./.local/query-generator.vite.config.ts:/usr/local/query-generator-ui/vite.config.ts
        labels:
            - traefik.http.routers.query-ui.rule=PathPrefix(`/query-ui`)
            - traefik.http.routers.query-ui.middlewares=forward-auth
            - application=nl2sql
    config-editor-ui:
        image: sbilifedockeradmin/config-editor-ui:latest
        restart: always
        networks:
            - nl2sql
        env_file: .local/config-editor-ui.env
        labels:
            - traefik.http.routers.file-editor-ui.rule=PathPrefix(`/editor-ui`)
            - traefik.http.routers.file-editor-ui.middlewares=forward-auth
            - application=nl2sql
    query-flow-batch-test:
        image: sbilifedockeradmin/query-flow-batch-test:latest
        networks:
            - nl2sql
        environment:
            - QUERY_FLOW_HOST=query-flow
            - DB_ID=nb
        volumes:
            - ./.local/.query-flow-batch-test:/var/lib/query-flow-batch-test:rw

networks:
    nl2sql:
        ipam:
            config:
                - subnet: 192.168.11.0/24
