[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "sbilifeco-boundary-tool-support"
version = "0.1.1"
description = "Support for tools for tool calls by LLMs"
dependencies = [
    "pydantic>=2.11.9"
]