[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "sbilifeco-cp-paths-metadata-storage"
version = "0.1.2"
description = "Paths for metadata storage microservice"
dependencies = []
