[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "sbilifeco-http-client-session-data-manager"
version = "0.1.0"
description = "HTTP client for session data manager microservice"
dependencies = [
    "requests>=2.32.4",
    "sbilifeco-boundary-session-data-manager>=0.1.0",
    "sbilifeco-models-base>=0.1.1",
    "sbilifeco-paths-session-data-manager>=0.1.0",
    "sbilifeco-cp-http-client>=0.1.1"
]