class EnvVars:
    test_type = "TEST_TYPE"
    http_port = "HTTP_PORT"
    staging_host = "STAGING_HOST"
    metadata_storage_host = "METADATA_STORAGE_HOST"
    metadata_storage_proto = "METADATA_STORAGE_PROTO"
    metadata_storage_port = "METADATA_STORAGE_PORT"
    vectoriser_proto = "VECTORSER_PROTO"
    vectoriser_host = "VECTORSER_HOST"
    vectoriser_port = "VECTORSER_PORT"
    vector_repo_proto = "VECTOR_REPO_PROTO"
    vector_repo_host = "VECTOR_REPO_HOST"
    vector_repo_port = "VECTOR_REPO_PORT"
    db_id = "DB_ID"


class Defaults:
    test_type = "unit"  # or "integration" or "staging"
    http_port = "80"
    staging_host = "localhost"
    metadata_storage_host = "localhost"
    metadata_storage_proto = "http"
    metadata_storage_port = "80"
    vectoriser_proto = "http"
    vectoriser_host = "localhost"
    vectoriser_port = "80"
    vector_repo_proto = "http"
    vector_repo_host = "localhost"
    vector_repo_port = "80"
