[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "sbilifeco-paths-session-data-manager"
version = "0.1.0"
description = "Paths and data structures for HTTP RFC"
dependencies = [
    "pydantic>=2.11.5"
]