[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sbilifeco-models-base"
version = "0.1.0"
description = "The most fundamental model classes for SbiLifeCo."
dependencies = []