[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "sbilifeco-models-base"
version = "0.1.2"
description = "The most fundamental model classes for SbiLifeCo."
dependencies = [
    "pydantic>=2.11.5"
]
