[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "sbilifeco-cp-microservice-query-flow"
version = "0.1.2"
description = "Microservice over query flow"
dependencies = [
    "sbilifeco-models-base>=0.1.1",
    "sbilifeco-cp-paths-query-flow>=0.1.1",
    "sbilifeco-cp-http-server>=0.1.1",
    "sbilifeco-user-flows-query-flow>=0.1.3",
]
