[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "sbilifeco-http-client-query-flow"
version = "0.1.6"
description = "HTTP client to access query flow microservice"
dependencies = [
    "requests>=2.32.3",
    "sbilifeco-models-base>=0.1.3",
    "sbilifeco-boundary-query-flow>=0.1.6",
    "sbilifeco-paths-query-flow>=0.1.3",
    "sbilifeco-cp-http-client>=0.1.2",
    "sbilifeco-http-client-llm>=0.1.6",
    "sbilifeco-http-client-metadata-storage>=0.1.5",
]
