[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sbilifeco-cp-http-client-query-flow"
version = "0.1.0"
description = "description"
dependencies = []